package ru.yandex.practicum.filmorate.storage.dao.query;

public enum Query {
    FIND_ALL_USERS,
    ADD_USER,
    ADD_FILM_GENRE,
    REMOVE_FILM_GENRES,
    UPDATE_USER,
    ADD_FRIEND_STATUS,
    REMOVE_USER_FRIEND,
    FIND_USER_FRIENDS,
    FIND_USER,
    ADD_FILM,
    UPDATE_FILM,
    ADD_LIKE,
    REMOVE_LIKE,
    GET_MOST_POPULAR_FILMS,
    FIND_ALL_FILMS,
    FIND_FILM,
    GET_FILM_LIKES,
    FIND_RATING,
    FIND_ALL_RATINGS,
    FIND_ALL_GENRES,
    FIND_GENRE,
    FIND_FILM_GENRES
}