FIND_ALL_USERS=SELECT * FROM users
FIND_ALL_FILMS=SELECT * FROM films
FIND_ALL_RATINGS=SELECT * FROM ratings
FIND_ALL_GENRES=SELECT * FROM genres
FIND_FILM=SELECT * FROM films WHERE film_id=?
FIND_USER=SELECT * FROM users WHERE user_id=?
FIND_GENRE=SELECT * FROM genres WHERE genre_id=?
FIND_RATING=SELECT * FROM ratings WHERE rating_id=?
GET_FILM_LIKES=SELECT user_id FROM favorite_films WHERE film_id=?
ADD_USER=INSERT INTO users(user_name, email, login, birthday) VALUES (?,?,?,?)
ADD_FILM=INSERT INTO films(rating_id, title, description, release_date, duration) VALUES (?,?,?,?,?)
ADD_FILM_GENRE=INSERT INTO film_genres (film_id, genre_id) VALUES (?,?)
ADD_LIKE=MERGE INTO favorite_films (user_id, film_id) KEY(user_id, film_id) VALUES (?, ?)
ADD_FRIEND_STATUS=MERGE INTO friendship (user_id, friend_id, status_id) KEY(user_id, friend_id) VALUES (?, ?, ?)
UPDATE_USER=UPDATE users SET user_name=?, email=?, login=?, birthday=? WHERE user_id=?
UPDATE_FILM=UPDATE films SET rating_id=?, title=?, description=?, release_date=?, duration=? WHERE film_id=?
REMOVE_USER_FRIEND=DELETE FROM friendship WHERE user_id=? AND friend_id=?
REMOVE_FILM_GENRES=DELETE FROM film_genres WHERE film_id=?
REMOVE_LIKE=DELETE FROM favorite_films WHERE film_id=? AND user_id=?
FIND_USER_FRIENDS=SELECT u.* FROM users u \
                  JOIN friendship f ON u.user_id = f.friend_id \
                  WHERE f.user_id=?
GET_MOST_POPULAR_FILMS=SELECT f.* FROM films f \
                       LEFT JOIN favorite_films ff ON f.film_id=ff.film_id \
                       GROUP BY f.film_id \
                       ORDER BY COUNT(ff.user_id) DESC LIMIT ?
FIND_FILM_GENRES=SELECT g.* FROM genres g \
                 JOIN film_genres f ON g.genre_id=f.genre_id \
                 WHERE f.film_id=?